package com.bt.ms.im.css.createequipmentorder.entity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-20T19:51:25.371+05:30
 * Generated source version: 3.4.3
 *
 */
@WebServiceClient(name = "EquipmentOrderService",
                  wsdlLocation = "file:/C:/Users/shwetha_somashekhara/Documents/MicroServices/Development%20V2/css-client/css-client-api-services/css-client-createequipmentorder/resources/www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0/EquipmentOrder.wsdl",
                  targetNamespace = "http://www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0")
public class EquipmentOrderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0", "EquipmentOrderService");
    public final static QName EquipmentOrder20 = new QName("http://www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0", "EquipmentOrder_2.0");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/shwetha_somashekhara/Documents/MicroServices/Development%20V2/css-client/css-client-api-services/css-client-createequipmentorder/resources/www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0/EquipmentOrder.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EquipmentOrderService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/shwetha_somashekhara/Documents/MicroServices/Development%20V2/css-client/css-client-api-services/css-client-createequipmentorder/resources/www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0/EquipmentOrder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EquipmentOrderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EquipmentOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EquipmentOrderService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EquipmentOrderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EquipmentOrderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EquipmentOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EquipmentOrder
     */
    @WebEndpoint(name = "EquipmentOrder_2.0")
    public EquipmentOrder getEquipmentOrder20() {
        return super.getPort(EquipmentOrder20, EquipmentOrder.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EquipmentOrder
     */
    @WebEndpoint(name = "EquipmentOrder_2.0")
    public EquipmentOrder getEquipmentOrder20(WebServiceFeature... features) {
        return super.getPort(EquipmentOrder20, EquipmentOrder.class, features);
    }

}
