package com.bt.ms.im.css.createequipmentorder.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.3
 * 2021-04-20T19:51:25.361+05:30
 * Generated source version: 3.4.3
 *
 */
@WebService(targetNamespace = "http://www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/v2.0", name = "EquipmentOrder")
@XmlSeeAlso({ObjectFactory.class})
public interface EquipmentOrder {

    /**
     * The EquipmentOrder.createEquipmentOrder is a facade web service for the Equipment Order (i.e. ORDERS05-ZEMMORDERS05) IDOC interface, which is used for placing the Corporate customer sales orders. This service accepts multiple order items (i.e. devices, SIMs or accessories) pertaining to new connections or upgrades.
     */
    @WebMethod
    @RequestWrapper(localName = "createEquipmentOrder", targetNamespace = "http://www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/EquipmentOrderRequest/v2.0", className = "com.bt.ms.im.css.order.entity.CreateEquipmentOrder")
    @ResponseWrapper(localName = "createEquipmentOrderResponse", targetNamespace = "http://www.ee.co.uk/generic_es/erp/sap/service/EquipmentOrder/EquipmentOrderResponse/v2.0", className = "com.bt.ms.im.css.order.entity.CreateEquipmentOrderResponse")
    public void createEquipmentOrder(

        @WebParam(name = "message", targetNamespace = "")
        com.bt.ms.im.css.createequipmentorder.entity.CreateEquipmentOrderRequest.Message message,
        @WebParam(mode = WebParam.Mode.OUT, name = "message", targetNamespace = "")
        javax.xml.ws.Holder<com.bt.ms.im.css.createequipmentorder.entity.CreateEquipmentOrderResponse.Message> message1,
        @WebParam(mode = WebParam.Mode.OUT, name = "orderReference", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> orderReference
    ) throws TechnicalFault, BusinessFault;
}
